# Generated by Django 3.0.8 on 2020-08-02 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessname', models.CharField(max_length=255)),
                ('businesstype', models.CharField(choices=[('restaurant', 'restaurant'), ('cosmetics', 'cosmetics'), ('clothing', 'clothing'), ('retail', 'retail'), ('freelance', 'freelance'), ('technology', 'technology'), ('Service Provider', 'Service Provider'), ('Commerce', 'Commerce')], max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('address2', models.CharField(default='None', max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(choices=[('Eastern Cape', 'Eastern Cape'), ('Free State', 'Free State'), ('Gauteng', 'Gauteng'), ('KwaZulu-Natal', 'KwaZulu-Natal'), ('Limpopo', 'Limpopo'), ('Mpumalanga', 'Mpumalanga'), ('Northern Cape', 'Northern Cape'), ('North West', 'North West'), ('Western Cape', 'Western Cape')], max_length=255)),
                ('postal_code', models.CharField(default='None', max_length=255)),
                ('logo', models.ImageField(default='None', upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('price', models.FloatField(max_length=10)),
                ('stock_quantity', models.IntegerField()),
                ('image', models.ImageField(default=None, upload_to='')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='businesses.Business')),
            ],
        ),
    ]
