# Generated by Django 3.0.8 on 2020-07-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessname', models.CharField(max_length=255)),
                ('facebook', models.BooleanField(default=False)),
                ('instagram', models.BooleanField(default=False)),
                ('google', models.BooleanField(default=False)),
                ('budget', models.CharField(max_length=200)),
                ('extrainfo', models.CharField(max_length=300)),
                ('budgetperiod', models.CharField(max_length=100)),
            ],
        ),
    ]
