# Generated by Django 3.0.8 on 2020-07-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_auto_20200731_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platforms',
            name='businessname',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
