# Generated by Django 3.0.8 on 2020-07-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_profile', '0002_auto_20200730_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='province',
            field=models.CharField(choices=[(1, 'Eastern Cape'), (2, 'Free State'), (3, 'Gauteng'), (4, 'KwaZulu-Natal'), (5, 'Limpopo'), (6, 'Mpumalanga'), (7, 'Northern Cape'), (8, 'North West'), (9, 'Western Cape')], max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(choices=[(1, 'Service Provider'), (2, 'Commerce')], max_length=255),
        ),
    ]
